### ISSUE TITLE
SSL握手异常

### ISSUE THREAD

**Issue by ikun-mr** [RafuiiChan/nonebot_plugin_charpic#3]
nonebot报错如下：
`
12-02 19:36:56 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_charpic, lineno=22) failed.
Traceback (most recent call last):
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_transports\default.py", line 101, in map_httpcore_exceptions
    yield
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_transports\default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_async\connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_async\http_proxy.py", line 316, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_async\http11.py", line 376, in start_tls
    return await self._stream.start_tls(ssl_context, server_hostname, timeout)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_backends\anyio.py", line 67, in start_tls
    with map_exceptions(exc_map):
  File "C:\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\drivers\quart.py", line 169, in run
    uvicorn.run(
  File "D:\alhsk_bot\.venv\Lib\site-packages\uvicorn\main.py", line 579, in run
    server.run()
  File "D:\alhsk_bot\.venv\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Python312\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\utils.py", line 254, in run_coro_with_shield
    return await coro
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 837, in simple_run
    await handler(
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot_plugin_charpic\__init__.py", line 44, in generate_
    pic = await get_img(img_urls[0])  # 取图
  File "D:\alhsk_bot\.venv\Lib\site-packages\nonebot_plugin_charpic\data_source.py", line 93, in get_img
    result = await client.get(img_url)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1770, in get
    return await self.request(
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1542, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1631, in send
    response = await self._send_handling_auth(
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1659, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1696, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_client.py", line 1732, in _send_single_request
    response = await transport.handle_async_request(request)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_transports\default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\alhsk_bot\.venv\Lib\site-packages\httpx\_transports\default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)
`

#### 使用的是onebotv11协议，前端为hook pcqq（liteloader的llqqnt插件），未启用**任何**代理

**Comment by 1umine** [comment]
看起来是 httpx / qqnt图片域名 的问题（或更深一点）

参考 https://github.com/encode/httpx/discussions/3214

**Comment by ikun-mr** [comment]
> 看起来是 httpx / qqnt图片域名 的问题（或更深一点）
> 
> 参考 [encode/httpx#3214](https://github.com/encode/httpx/discussions/3214)

所以我可以怎么做，等吗？

**Comment by 1umine** [comment]
我是 python3.11，fastapi(默认驱动器)，httpx==0.25.1 环境，没有碰到这个问题
没有不得不使用现有驱动器以及Python版本的话，可以试试更换Python版本，httpx 版本

**Comment by ikun-mr** [comment]
> 我是 python3.11，fastapi(默认驱动器)，httpx==0.25.1 环境，没有碰到这个问题 没有不得不使用现有驱动器以及Python版本的话，可以试试更换Python版本，httpx 版本

那我换个httpx试试
我可不想等py安装了（晕）

**Comment by ikun-mr** [comment]
省流：httpx版本干的
插件要求0.27,实则0.25.1就ok了
